version: "3.9"

services:
  postgres:
    image: postgres:14
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      ./.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - ../pgdata:/var/lib/postgresql/data

  server:
    container_name: prakticum-server
    image: prackicum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
        NODE_ENV: ${NODE_ENV}
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
      - "24678:24678"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      NODE_ENV: ${NODE_ENV}
    env_file:
      ./.env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: